name: Quality

on:
  merge_group:
  pull_request:
    branches:
      - main

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        env :
          CI: true
        run: |
          npm pkg delete scripts.prepare
          npm ci

      - name: Run JS and CSS linters
        run: |
          npm run eslint && npm run stylelint
